uber_provided_example:
  azureml:
    dataset: 
      name: "iclaims"
  utils:
    TIME_COL: "week"
    RESPONSE_COL: "claims"
    test_ind: 52
    seed: 8888
    global_trend_option_list:
    - linear
    - loglinear
    - logistic
    - flat
  dlt_map:
    estimator: "stan-map"
    seasonality: 52
  dlt_full:
    estimator: "stan-mcmc"
    seasonality: 52
    point_method: ~
  dlt_agg:
    estimator: "stan-mcmc"
    seasonality: 52
    point_method: "mean"
  lgt_map:
    regressor_col: "sp500"
    estimator: "stan-map"
    seasonality: 52
  lgt_full:
    regressor_col: "sp500"
    estimator: "stan-mcmc"
    seasonality: 52
    point_method: ~
  lgt_agg:
    regressor_col: "sp500"
    estimator: "pyro-svi"
    seasonality: 52
    point_method: ~